DROP TRIGGER IF EXISTS tg_CriptografaSenha

GO

CREATE TRIGGER tg_CriptografaSenha
On Usuario
AFTER INSERT
AS
	DECLARE  @ID_USUARIO	INT
			,@SENHA			VARCHAR(64)
			,@HASH			VARBINARY(MAX)

	SELECT @ID_USUARIO	 = I.ID_Usuario
		  ,@SENHA		 = I.Senha	
		FROM INSERTED AS I

	SET @HASH = HASHBYTES('SHA2_256', @SENHA)

	UPDATE Usuario SET Senha = CONVERT(VARCHAR(65), @HASH, 2)
	WHERE ID_Usuario = @ID_USUARIO

