#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MaryKay")]
	public partial class BaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertTipo_Produto(Tipo_Produto instance);
    partial void UpdateTipo_Produto(Tipo_Produto instance);
    partial void DeleteTipo_Produto(Tipo_Produto instance);
    partial void InsertVenda_Cliente(Venda_Cliente instance);
    partial void UpdateVenda_Cliente(Venda_Cliente instance);
    partial void DeleteVenda_Cliente(Venda_Cliente instance);
    partial void InsertProduto(Produto instance);
    partial void UpdateProduto(Produto instance);
    partial void DeleteProduto(Produto instance);
    partial void InsertEstoque(Estoque instance);
    partial void UpdateEstoque(Estoque instance);
    partial void DeleteEstoque(Estoque instance);
    #endregion
		
		public BaseDataContext() : 
				base(global::DAL.Properties.Settings.Default.MaryKayConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_Produto> Tipo_Produtos
		{
			get
			{
				return this.GetTable<Tipo_Produto>();
			}
		}
		
		public System.Data.Linq.Table<Venda_Cliente> Venda_Clientes
		{
			get
			{
				return this.GetTable<Venda_Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Produto> Produtos
		{
			get
			{
				return this.GetTable<Produto>();
			}
		}
		
		public System.Data.Linq.Table<Estoque> Estoques
		{
			get
			{
				return this.GetTable<Estoque>();
			}
		}
		
		public System.Data.Linq.Table<vw_Produto> vw_Produtos
		{
			get
			{
				return this.GetTable<vw_Produto>();
			}
		}
		
		public System.Data.Linq.Table<vw_Estoque> vw_Estoques
		{
			get
			{
				return this.GetTable<vw_Estoque>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlterarEstoque")]
		public int usp_AlterarEstoque([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Produto", DbType="Int")] System.Nullable<int> iD_Produto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantidade", DbType="Int")] System.Nullable<int> quantidade)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Produto, quantidade);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Cliente;
		
		private System.Nullable<int> _ID_Usuario;
		
		private string _Nome;
		
		private string _CPF;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DT_Nascimento;
		
		private string _Telefone;
		
		private string _Rua;
		
		private int _CEP;
		
		private System.Nullable<int> _NR_Logradouro;
		
		private string _Estado;
		
		private string _Cidade;
		
		private System.Nullable<bool> _FL_EnviaEmail;
		
		private EntitySet<Venda_Cliente> _Venda_Clientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ClienteChanging(int value);
    partial void OnID_ClienteChanged();
    partial void OnID_UsuarioChanging(System.Nullable<int> value);
    partial void OnID_UsuarioChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDT_NascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_NascimentoChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnRuaChanging(string value);
    partial void OnRuaChanged();
    partial void OnCEPChanging(int value);
    partial void OnCEPChanged();
    partial void OnNR_LogradouroChanging(System.Nullable<int> value);
    partial void OnNR_LogradouroChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnFL_EnviaEmailChanging(System.Nullable<bool> value);
    partial void OnFL_EnviaEmailChanged();
    #endregion
		
		public Cliente()
		{
			this._Venda_Clientes = new EntitySet<Venda_Cliente>(new Action<Venda_Cliente>(this.attach_Venda_Clientes), new Action<Venda_Cliente>(this.detach_Venda_Clientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Cliente
		{
			get
			{
				return this._ID_Cliente;
			}
			set
			{
				if ((this._ID_Cliente != value))
				{
					this.OnID_ClienteChanging(value);
					this.SendPropertyChanging();
					this._ID_Cliente = value;
					this.SendPropertyChanged("ID_Cliente");
					this.OnID_ClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario", DbType="Int")]
		public System.Nullable<int> ID_Usuario
		{
			get
			{
				return this._ID_Usuario;
			}
			set
			{
				if ((this._ID_Usuario != value))
				{
					this.OnID_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._ID_Usuario = value;
					this.SendPropertyChanged("ID_Usuario");
					this.OnID_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(11)")]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Nascimento", DbType="Date")]
		public System.Nullable<System.DateTime> DT_Nascimento
		{
			get
			{
				return this._DT_Nascimento;
			}
			set
			{
				if ((this._DT_Nascimento != value))
				{
					this.OnDT_NascimentoChanging(value);
					this.SendPropertyChanging();
					this._DT_Nascimento = value;
					this.SendPropertyChanged("DT_Nascimento");
					this.OnDT_NascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rua", DbType="VarChar(100)")]
		public string Rua
		{
			get
			{
				return this._Rua;
			}
			set
			{
				if ((this._Rua != value))
				{
					this.OnRuaChanging(value);
					this.SendPropertyChanging();
					this._Rua = value;
					this.SendPropertyChanged("Rua");
					this.OnRuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="Int NOT NULL")]
		public int CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_Logradouro", DbType="Int")]
		public System.Nullable<int> NR_Logradouro
		{
			get
			{
				return this._NR_Logradouro;
			}
			set
			{
				if ((this._NR_Logradouro != value))
				{
					this.OnNR_LogradouroChanging(value);
					this.SendPropertyChanging();
					this._NR_Logradouro = value;
					this.SendPropertyChanged("NR_Logradouro");
					this.OnNR_LogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(50)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(100)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FL_EnviaEmail", DbType="Bit")]
		public System.Nullable<bool> FL_EnviaEmail
		{
			get
			{
				return this._FL_EnviaEmail;
			}
			set
			{
				if ((this._FL_EnviaEmail != value))
				{
					this.OnFL_EnviaEmailChanging(value);
					this.SendPropertyChanging();
					this._FL_EnviaEmail = value;
					this.SendPropertyChanged("FL_EnviaEmail");
					this.OnFL_EnviaEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Venda_Cliente", Storage="_Venda_Clientes", ThisKey="ID_Cliente", OtherKey="ID_Cliente")]
		public EntitySet<Venda_Cliente> Venda_Clientes
		{
			get
			{
				return this._Venda_Clientes;
			}
			set
			{
				this._Venda_Clientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Venda_Clientes(Venda_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Venda_Clientes(Venda_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_Produto")]
	public partial class Tipo_Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TipoProduto;
		
		private string _Categoria;
		
		private EntitySet<Produto> _Produtos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TipoProdutoChanging(int value);
    partial void OnID_TipoProdutoChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    #endregion
		
		public Tipo_Produto()
		{
			this._Produtos = new EntitySet<Produto>(new Action<Produto>(this.attach_Produtos), new Action<Produto>(this.detach_Produtos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TipoProduto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TipoProduto
		{
			get
			{
				return this._ID_TipoProduto;
			}
			set
			{
				if ((this._ID_TipoProduto != value))
				{
					this.OnID_TipoProdutoChanging(value);
					this.SendPropertyChanging();
					this._ID_TipoProduto = value;
					this.SendPropertyChanged("ID_TipoProduto");
					this.OnID_TipoProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_Produto_Produto", Storage="_Produtos", ThisKey="ID_TipoProduto", OtherKey="ID_TipoProduto")]
		public EntitySet<Produto> Produtos
		{
			get
			{
				return this._Produtos;
			}
			set
			{
				this._Produtos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Produtos(Produto entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_Produto = this;
		}
		
		private void detach_Produtos(Produto entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Venda_Cliente")]
	public partial class Venda_Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Venda;
		
		private System.Nullable<int> _ID_Produto;
		
		private System.Nullable<int> _ID_Cliente;
		
		private System.DateTime _DT_Venda;
		
		private int _QTD_Item;
		
		private decimal _VL_Total;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Produto> _Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VendaChanging(int value);
    partial void OnID_VendaChanged();
    partial void OnID_ProdutoChanging(System.Nullable<int> value);
    partial void OnID_ProdutoChanged();
    partial void OnID_ClienteChanging(System.Nullable<int> value);
    partial void OnID_ClienteChanged();
    partial void OnDT_VendaChanging(System.DateTime value);
    partial void OnDT_VendaChanged();
    partial void OnQTD_ItemChanging(int value);
    partial void OnQTD_ItemChanged();
    partial void OnVL_TotalChanging(decimal value);
    partial void OnVL_TotalChanged();
    #endregion
		
		public Venda_Cliente()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Produto = default(EntityRef<Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Venda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Venda
		{
			get
			{
				return this._ID_Venda;
			}
			set
			{
				if ((this._ID_Venda != value))
				{
					this.OnID_VendaChanging(value);
					this.SendPropertyChanging();
					this._ID_Venda = value;
					this.SendPropertyChanged("ID_Venda");
					this.OnID_VendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Produto", DbType="Int")]
		public System.Nullable<int> ID_Produto
		{
			get
			{
				return this._ID_Produto;
			}
			set
			{
				if ((this._ID_Produto != value))
				{
					if (this._Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ProdutoChanging(value);
					this.SendPropertyChanging();
					this._ID_Produto = value;
					this.SendPropertyChanged("ID_Produto");
					this.OnID_ProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cliente", DbType="Int")]
		public System.Nullable<int> ID_Cliente
		{
			get
			{
				return this._ID_Cliente;
			}
			set
			{
				if ((this._ID_Cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ClienteChanging(value);
					this.SendPropertyChanging();
					this._ID_Cliente = value;
					this.SendPropertyChanged("ID_Cliente");
					this.OnID_ClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Venda", DbType="DateTime NOT NULL")]
		public System.DateTime DT_Venda
		{
			get
			{
				return this._DT_Venda;
			}
			set
			{
				if ((this._DT_Venda != value))
				{
					this.OnDT_VendaChanging(value);
					this.SendPropertyChanging();
					this._DT_Venda = value;
					this.SendPropertyChanged("DT_Venda");
					this.OnDT_VendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTD_Item", DbType="Int NOT NULL")]
		public int QTD_Item
		{
			get
			{
				return this._QTD_Item;
			}
			set
			{
				if ((this._QTD_Item != value))
				{
					this.OnQTD_ItemChanging(value);
					this.SendPropertyChanging();
					this._QTD_Item = value;
					this.SendPropertyChanged("QTD_Item");
					this.OnQTD_ItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_Total", DbType="Decimal(5,2) NOT NULL")]
		public decimal VL_Total
		{
			get
			{
				return this._VL_Total;
			}
			set
			{
				if ((this._VL_Total != value))
				{
					this.OnVL_TotalChanging(value);
					this.SendPropertyChanging();
					this._VL_Total = value;
					this.SendPropertyChanged("VL_Total");
					this.OnVL_TotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Venda_Cliente", Storage="_Cliente", ThisKey="ID_Cliente", OtherKey="ID_Cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Venda_Clientes.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Venda_Clientes.Add(this);
						this._ID_Cliente = value.ID_Cliente;
					}
					else
					{
						this._ID_Cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Venda_Cliente", Storage="_Produto", ThisKey="ID_Produto", OtherKey="ID_Produto", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.Venda_Clientes.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.Venda_Clientes.Add(this);
						this._ID_Produto = value.ID_Produto;
					}
					else
					{
						this._ID_Produto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produto")]
	public partial class Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Produto;
		
		private int _ID_TipoProduto;
		
		private string _Nome;
		
		private int _Codigo;
		
		private System.Nullable<int> _Ponto;
		
		private decimal _VL_Pago;
		
		private decimal _VL_Venda;
		
		private int _Sessao;
		
		private System.Nullable<decimal> _Lucro;
		
		private EntitySet<Venda_Cliente> _Venda_Clientes;
		
		private EntitySet<Estoque> _Estoques;
		
		private EntityRef<Tipo_Produto> _Tipo_Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ProdutoChanging(int value);
    partial void OnID_ProdutoChanged();
    partial void OnID_TipoProdutoChanging(int value);
    partial void OnID_TipoProdutoChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnPontoChanging(System.Nullable<int> value);
    partial void OnPontoChanged();
    partial void OnVL_PagoChanging(decimal value);
    partial void OnVL_PagoChanged();
    partial void OnVL_VendaChanging(decimal value);
    partial void OnVL_VendaChanged();
    partial void OnSessaoChanging(int value);
    partial void OnSessaoChanged();
    partial void OnLucroChanging(System.Nullable<decimal> value);
    partial void OnLucroChanged();
    #endregion
		
		public Produto()
		{
			this._Venda_Clientes = new EntitySet<Venda_Cliente>(new Action<Venda_Cliente>(this.attach_Venda_Clientes), new Action<Venda_Cliente>(this.detach_Venda_Clientes));
			this._Estoques = new EntitySet<Estoque>(new Action<Estoque>(this.attach_Estoques), new Action<Estoque>(this.detach_Estoques));
			this._Tipo_Produto = default(EntityRef<Tipo_Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Produto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Produto
		{
			get
			{
				return this._ID_Produto;
			}
			set
			{
				if ((this._ID_Produto != value))
				{
					this.OnID_ProdutoChanging(value);
					this.SendPropertyChanging();
					this._ID_Produto = value;
					this.SendPropertyChanged("ID_Produto");
					this.OnID_ProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TipoProduto", DbType="Int NOT NULL")]
		public int ID_TipoProduto
		{
			get
			{
				return this._ID_TipoProduto;
			}
			set
			{
				if ((this._ID_TipoProduto != value))
				{
					if (this._Tipo_Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TipoProdutoChanging(value);
					this.SendPropertyChanging();
					this._ID_TipoProduto = value;
					this.SendPropertyChanged("ID_TipoProduto");
					this.OnID_TipoProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL")]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ponto", DbType="Int")]
		public System.Nullable<int> Ponto
		{
			get
			{
				return this._Ponto;
			}
			set
			{
				if ((this._Ponto != value))
				{
					this.OnPontoChanging(value);
					this.SendPropertyChanging();
					this._Ponto = value;
					this.SendPropertyChanged("Ponto");
					this.OnPontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_Pago", DbType="Decimal(5,2) NOT NULL")]
		public decimal VL_Pago
		{
			get
			{
				return this._VL_Pago;
			}
			set
			{
				if ((this._VL_Pago != value))
				{
					this.OnVL_PagoChanging(value);
					this.SendPropertyChanging();
					this._VL_Pago = value;
					this.SendPropertyChanged("VL_Pago");
					this.OnVL_PagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VL_Venda", DbType="Decimal(5,2) NOT NULL")]
		public decimal VL_Venda
		{
			get
			{
				return this._VL_Venda;
			}
			set
			{
				if ((this._VL_Venda != value))
				{
					this.OnVL_VendaChanging(value);
					this.SendPropertyChanging();
					this._VL_Venda = value;
					this.SendPropertyChanged("VL_Venda");
					this.OnVL_VendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sessao", DbType="Int NOT NULL")]
		public int Sessao
		{
			get
			{
				return this._Sessao;
			}
			set
			{
				if ((this._Sessao != value))
				{
					this.OnSessaoChanging(value);
					this.SendPropertyChanging();
					this._Sessao = value;
					this.SendPropertyChanged("Sessao");
					this.OnSessaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lucro", AutoSync=AutoSync.Always, DbType="Decimal(6,2)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Lucro
		{
			get
			{
				return this._Lucro;
			}
			set
			{
				if ((this._Lucro != value))
				{
					this.OnLucroChanging(value);
					this.SendPropertyChanging();
					this._Lucro = value;
					this.SendPropertyChanged("Lucro");
					this.OnLucroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Venda_Cliente", Storage="_Venda_Clientes", ThisKey="ID_Produto", OtherKey="ID_Produto")]
		public EntitySet<Venda_Cliente> Venda_Clientes
		{
			get
			{
				return this._Venda_Clientes;
			}
			set
			{
				this._Venda_Clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Estoque", Storage="_Estoques", ThisKey="ID_Produto", OtherKey="ID_Produto")]
		public EntitySet<Estoque> Estoques
		{
			get
			{
				return this._Estoques;
			}
			set
			{
				this._Estoques.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_Produto_Produto", Storage="_Tipo_Produto", ThisKey="ID_TipoProduto", OtherKey="ID_TipoProduto", IsForeignKey=true)]
		public Tipo_Produto Tipo_Produto
		{
			get
			{
				return this._Tipo_Produto.Entity;
			}
			set
			{
				Tipo_Produto previousValue = this._Tipo_Produto.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_Produto.Entity = null;
						previousValue.Produtos.Remove(this);
					}
					this._Tipo_Produto.Entity = value;
					if ((value != null))
					{
						value.Produtos.Add(this);
						this._ID_TipoProduto = value.ID_TipoProduto;
					}
					else
					{
						this._ID_TipoProduto = default(int);
					}
					this.SendPropertyChanged("Tipo_Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Venda_Clientes(Venda_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_Venda_Clientes(Venda_Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
		
		private void attach_Estoques(Estoque entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_Estoques(Estoque entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estoque")]
	public partial class Estoque : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Estoque;
		
		private int _ID_Produto;
		
		private int _QTD_Item;
		
		private EntityRef<Produto> _Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EstoqueChanging(int value);
    partial void OnID_EstoqueChanged();
    partial void OnID_ProdutoChanging(int value);
    partial void OnID_ProdutoChanged();
    partial void OnQTD_ItemChanging(int value);
    partial void OnQTD_ItemChanged();
    #endregion
		
		public Estoque()
		{
			this._Produto = default(EntityRef<Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Estoque", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Estoque
		{
			get
			{
				return this._ID_Estoque;
			}
			set
			{
				if ((this._ID_Estoque != value))
				{
					this.OnID_EstoqueChanging(value);
					this.SendPropertyChanging();
					this._ID_Estoque = value;
					this.SendPropertyChanged("ID_Estoque");
					this.OnID_EstoqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Produto", DbType="Int NOT NULL")]
		public int ID_Produto
		{
			get
			{
				return this._ID_Produto;
			}
			set
			{
				if ((this._ID_Produto != value))
				{
					if (this._Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ProdutoChanging(value);
					this.SendPropertyChanging();
					this._ID_Produto = value;
					this.SendPropertyChanged("ID_Produto");
					this.OnID_ProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTD_Item", DbType="Int NOT NULL")]
		public int QTD_Item
		{
			get
			{
				return this._QTD_Item;
			}
			set
			{
				if ((this._QTD_Item != value))
				{
					this.OnQTD_ItemChanging(value);
					this.SendPropertyChanging();
					this._QTD_Item = value;
					this.SendPropertyChanged("QTD_Item");
					this.OnQTD_ItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_Estoque", Storage="_Produto", ThisKey="ID_Produto", OtherKey="ID_Produto", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.Estoques.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.Estoques.Add(this);
						this._ID_Produto = value.ID_Produto;
					}
					else
					{
						this._ID_Produto = default(int);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_Produtos")]
	public partial class vw_Produto
	{
		
		private int _ID_Produto;
		
		private string _NOME;
		
		private string _CATEGORIA_DO_PRODUTO;
		
		private int _CÓDIGO_RÁPIDO;
		
		private System.Nullable<int> _PONTOS;
		
		private decimal _VALOR_DE_COMPRA;
		
		private decimal _VALOR_DE_VENDA;
		
		private System.Nullable<decimal> _LUCRO;
		
		private int _SESSÃO;
		
		public vw_Produto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Produto", DbType="Int NOT NULL")]
		public int ID_Produto
		{
			get
			{
				return this._ID_Produto;
			}
			set
			{
				if ((this._ID_Produto != value))
				{
					this._ID_Produto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this._NOME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CATEGORIA DO PRODUTO]", Storage="_CATEGORIA_DO_PRODUTO", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CATEGORIA_DO_PRODUTO
		{
			get
			{
				return this._CATEGORIA_DO_PRODUTO;
			}
			set
			{
				if ((this._CATEGORIA_DO_PRODUTO != value))
				{
					this._CATEGORIA_DO_PRODUTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CÓDIGO RÁPIDO]", Storage="_CÓDIGO_RÁPIDO", DbType="Int NOT NULL")]
		public int CÓDIGO_RÁPIDO
		{
			get
			{
				return this._CÓDIGO_RÁPIDO;
			}
			set
			{
				if ((this._CÓDIGO_RÁPIDO != value))
				{
					this._CÓDIGO_RÁPIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PONTOS", DbType="Int")]
		public System.Nullable<int> PONTOS
		{
			get
			{
				return this._PONTOS;
			}
			set
			{
				if ((this._PONTOS != value))
				{
					this._PONTOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[VALOR DE COMPRA]", Storage="_VALOR_DE_COMPRA", DbType="Decimal(5,2) NOT NULL")]
		public decimal VALOR_DE_COMPRA
		{
			get
			{
				return this._VALOR_DE_COMPRA;
			}
			set
			{
				if ((this._VALOR_DE_COMPRA != value))
				{
					this._VALOR_DE_COMPRA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[VALOR DE VENDA]", Storage="_VALOR_DE_VENDA", DbType="Decimal(5,2) NOT NULL")]
		public decimal VALOR_DE_VENDA
		{
			get
			{
				return this._VALOR_DE_VENDA;
			}
			set
			{
				if ((this._VALOR_DE_VENDA != value))
				{
					this._VALOR_DE_VENDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCRO", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> LUCRO
		{
			get
			{
				return this._LUCRO;
			}
			set
			{
				if ((this._LUCRO != value))
				{
					this._LUCRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSÃO", DbType="Int NOT NULL")]
		public int SESSÃO
		{
			get
			{
				return this._SESSÃO;
			}
			set
			{
				if ((this._SESSÃO != value))
				{
					this._SESSÃO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_Estoque")]
	public partial class vw_Estoque
	{
		
		private string _NOME;
		
		private string _CATEGORIA;
		
		private int _QUANTIDADE;
		
		private decimal _COMPRA;
		
		private decimal _VENDA;
		
		private System.Nullable<decimal> _LUCRO;
		
		private System.Nullable<int> _TOTAL_DE_UNIDADES_VENDIDAS;
		
		public vw_Estoque()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this._NOME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CATEGORIA
		{
			get
			{
				return this._CATEGORIA;
			}
			set
			{
				if ((this._CATEGORIA != value))
				{
					this._CATEGORIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTIDADE", DbType="Int NOT NULL")]
		public int QUANTIDADE
		{
			get
			{
				return this._QUANTIDADE;
			}
			set
			{
				if ((this._QUANTIDADE != value))
				{
					this._QUANTIDADE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPRA", DbType="Decimal(5,2) NOT NULL")]
		public decimal COMPRA
		{
			get
			{
				return this._COMPRA;
			}
			set
			{
				if ((this._COMPRA != value))
				{
					this._COMPRA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VENDA", DbType="Decimal(5,2) NOT NULL")]
		public decimal VENDA
		{
			get
			{
				return this._VENDA;
			}
			set
			{
				if ((this._VENDA != value))
				{
					this._VENDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUCRO", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> LUCRO
		{
			get
			{
				return this._LUCRO;
			}
			set
			{
				if ((this._LUCRO != value))
				{
					this._LUCRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[TOTAL DE UNIDADES VENDIDAS]", Storage="_TOTAL_DE_UNIDADES_VENDIDAS", DbType="Int")]
		public System.Nullable<int> TOTAL_DE_UNIDADES_VENDIDAS
		{
			get
			{
				return this._TOTAL_DE_UNIDADES_VENDIDAS;
			}
			set
			{
				if ((this._TOTAL_DE_UNIDADES_VENDIDAS != value))
				{
					this._TOTAL_DE_UNIDADES_VENDIDAS = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
